### ISSUE TITLE
Forge Warning

### ISSUE THREAD

**Issue by xoltiv** [GirafiStudios/BetterTitleScreen#12]
Upon launching the game, Forge spits out a warning saying "File Mod File: (mod path) failed to load a valid ResourcePackInfo"

I'm using Forge 1.15.1 30.0.35 and BetterTitleScreen 1.8.

**Comment by GirafiStudios** [comment]
It's nothing to worry about, it's just because BTS is not using the new resource pack format yet. It won't matter at all since BTS have no textures etc.

**Comment by GirafiStudios** [comment]
Oh there was actually a comma in the file that shouldn't be there.
Still won't affect anything, but I've pushed a fix to Github now.
