### ISSUE TITLE
Suggestion: Option to hide the "New Forge version available" message

### ISSUE THREAD

**Issue by ChatFawkes** [GirafiStudios/BetterTitleScreen#2]
Would be nice if to have an option to hide the "New Forge version available:" message on the right hand side:
![2014-10-25_01 01 12](http://i.imgur.com/O54DQhu.png?1)

**Comment by GirafiStudios** [comment]
Version Check is fixed in Minecraft Forge for both Minecraft 1.7.10 and 1.8 now.
