### ISSUE TITLE
1.16.1 weird issue

### ISSUE THREAD

**Issue by BedrockLegends** [GirafiStudios/BetterTitleScreen#21]
After I put I changed somethings in the config  it did this in the image, Note that the stuff in the config did not work right.

https://gist.github.com/BedrockLegends/87ab8353b5891a4f8e6f4c2e5fefb098

![2020-07-01_11 36 09](https://user-images.githubusercontent.com/48525410/86269239-15e0e880-bb8f-11ea-8031-c1682c3f2222.png)

**Comment by GirafiStudios** [comment]
Unable to reproduce. I suspect that whatever adds your Discord-button is causing the issue.
![OB0lnMs](https://user-images.githubusercontent.com/6305377/86270199-22833200-bbcb-11ea-96a5-3b237ab2cef9.jpg)
