### ISSUE TITLE
It says "(supports multiple lines)" but how do you do that?

### ISSUE THREAD

**Issue by Lucas4545ah** [GirafiStudios/BetterTitleScreen#23]
![image](https://user-images.githubusercontent.com/52332868/111041812-ffae4c00-83ee-11eb-8d3b-6e1341488898.png)
It says that but, not how to do multiple lines.

I am thinking you may need to use "/n" but yeah.

**Comment by GirafiStudios** [comment]
text = ["Line 1", "Line2", "Line3"]

**Comment by Lucas4545ah** [comment]
Thank you!

**Comment by Automatiic** [comment]
> text = ["Line 1", "Line2", "Line3"]

could you put this on this main page? i had the exact same issue and had to hunt for it here
