### ISSUE TITLE
Can I transfer this MOD to Chinese Website MCBBS?

### ISSUE THREAD

**Issue by 2173204318** [GirafiStudios/BetterTitleScreen#24]
It's a great MOD,I want to transfer this MOD to Chinese Website www.mcbbs.net.
I'll link to Curseforge pages and don't provide download pages,It's just an introduction.

**Comment by GirafiStudios** [comment]
You're welcome to do so, as long as you don't host any mod files, and link to CurseForge instead 🙂

**Comment by 2173204318** [comment]
> You're welcome to do so, as long as you don't host any mod files, and link to CurseForge instead 🙂

Thank you!
