### ISSUE TITLE
add an option to hide 5zig text in the title screen

### ISSUE THREAD

**Issue by somerandomstick** [GirafiStudios/BetterTitleScreen#30]
this is more of a suggestion than a bug, but mind adding an option to hide the text from 5zig mod in the title screen? a lot of people use this mod and it annoyingly creates its own text on the top left of the title screen so yeah, It'll be nice if you add an option to hide it.
![5zig text on title screen](https://user-images.githubusercontent.com/103639524/163376558-d6ccbfd0-1856-44ff-a55f-e279439ba2c5.png)
.

**Comment by GirafiStudios** [comment]
Potientially, Im not familiar with the mod though.
Could you provide a link?

**Comment by somerandomstick** [comment]
https://5zigreborn.eu/

**Comment by GirafiStudios** [comment]
The mod only have Forge support up to 1.15.2, which is no longer supported by BTS.

**Comment by somerandomstick** [comment]
can't you do it for the versions that it does support?

**Comment by GirafiStudios** [comment]
No, I've not supported 1.15.2 for years.
