### ISSUE TITLE
Resetting the main window after exiting the game world

### ISSUE THREAD

**Issue by WantaSanches** [GirafiStudios/BetterTitleScreen#31]
After updating to Forge 40.1.0 and higher, when you exit the game world, the title screen is displayed in the main menu, whether your mod is not installed.

**Comment by GirafiStudios** [comment]
I´m not exactly sure what you´re saying. Could you provide a screenshot?

**Comment by WantaSanches** [comment]
Sorry, I don't know English well and I use a translator. I will make a video to show the problem. Give me a few hours.

**Comment by WantaSanches** [comment]
When I shot the video, I noticed that after reloading the resources (for example, after changing the resource pack), the title menu is also reset. Below is a link to the recording (can I take a record in more detail?). Recording at the standard settings of your mod.

[https://youtu.be/foY-lgAAd7U](url)

**Comment by GirafiStudios** [comment]
I understand your problem now, thanks for the video!
Unfortunately it works perfectly fine for me. Still shows up perfectly fine when going into a world & out again. Tested with same Forge version as you did.

**Comment by WantaSanches** [comment]
But then why does mod work so poorly? Could this be due to using a third party JRE (I'm using Adoptium JRE 17.0.3+7)?

**Comment by GirafiStudios** [comment]
That could very well be the issue, yes :)
Either Oracle Java or OpenJDK should work.

**Comment by WantaSanches** [comment]
Well, if you suddenly need additional information about this, let me know, I can provide everything in my opportunities.

<h2 align="center">Good luck with the mod! :D</h2>
