### ISSUE TITLE
the changes do not show after reloading textures or changes on the options

### ISSUE THREAD

**Issue by OlaPessoa** [GirafiStudios/BetterTitleScreen#32]
,

**Comment by GirafiStudios** [comment]
What version of Better Title Screen are you using?

**Comment by GirafiStudios** [comment]
You need to restart the game, for the changes for take affect. Reloading the resourcepack no longer works on recent Minecraft version.

**Comment by OlaPessoa** [comment]
i'm not saying i'm trying to reload the resourcepacks to reload the config, THE MOD DOESNT WORK AFTER RELOADING RESOURCEPACKS, the title screen gets back to normal, i'm using version 1.13.2 for 1.20.1
