### ISSUE TITLE
Forge Minimum error (1.8)

### ISSUE THREAD

**Issue by xZennoNx** [GirafiStudios/BetterTitleScreen#7]
Hello,

I have encountered an error for the 1.8 version. It says (when I load up with the mod) "Forge" minimum version required is 11.14.0.1237" and there is no such Forge version for 1.8 out yet.
Am I doing something wrong?

![images](https://cloud.githubusercontent.com/assets/11651376/6830175/099d480c-d37d-11e4-8c14-b6ee993602a5.png)

**Comment by GirafiStudios** [comment]
The version is indeed out, it's just a really old version of Minecraft Forge for 1.8, because i updated the mod just after Minecraft Forge for 1.8 came out.
To me it looks like you don't have Minecraft Forge installed at all, but only liteloader.
