### ISSUE TITLE
(Issue removed)

### ISSUE THREAD

**Issue by Mixbeam** [GirafiStudios/BetterTitleScreen#9]
(ISSUE REMOVED I HAD TO RESTART MC)

**Comment by Mixbeam** [comment]
1.8.9 Version

**Comment by Mixbeam** [comment]
Fix it for 1.8.9

**Comment by Mixbeam** [comment]
or i hate u m8

**Comment by GirafiStudios** [comment]
I'm not even gonna attempt to fix anything, when you talk like that. Hate me all you want.
